<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-25T10:11:52 EEST" name="Default suite" finished-at="2024-07-25T10:11:58 EEST" duration-ms="6346">
    <groups>
      <group name="Negative">
        <method signature="T02_Login.TestInvalidPasswordLogin_N()[pri:2, instance:tests.T02_Login@4dc27487]" name="TestInvalidPasswordLogin_N" class="tests.T02_Login"/>
        <method signature="T02_Login.TestInvalidEmailLogin_N()[pri:3, instance:tests.T02_Login@4dc27487]" name="TestInvalidEmailLogin_N" class="tests.T02_Login"/>
      </group> <!-- Negative -->
    </groups>
    <test started-at="2024-07-25T10:11:52 EEST" name="Default test" finished-at="2024-07-25T10:11:58 EEST" duration-ms="6346">
      <class name="tests.T02_Login">
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.T02_Login@4dc27487]" started-at="2024-07-25T10:11:52 EEST" name="setUp" finished-at="2024-07-25T10:11:55 EEST" duration-ms="3383" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="generateData()[pri:0, instance:tests.T02_Login@4dc27487]" started-at="2024-07-25T10:11:55 EEST" name="generateData" finished-at="2024-07-25T10:11:55 EEST" duration-ms="248" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateData -->
        <test-method signature="TestLogin_P()[pri:1, instance:tests.T02_Login@4dc27487]" started-at="2024-07-25T10:11:55 EEST" name="TestLogin_P" finished-at="2024-07-25T10:11:56 EEST" duration-ms="983" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [nopCommerce demo store] but found [nopCommerce demo store. Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [nopCommerce demo store] but found [nopCommerce demo store. Login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at tests.T02_Login.TestLogin_P(T02_Login.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLogin_P -->
        <test-method signature="TestInvalidPasswordLogin_N()[pri:2, instance:tests.T02_Login@4dc27487]" started-at="2024-07-25T10:11:56 EEST" name="TestInvalidPasswordLogin_N" finished-at="2024-07-25T10:11:57 EEST" duration-ms="788" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInvalidPasswordLogin_N -->
        <test-method signature="TestInvalidEmailLogin_N()[pri:3, instance:tests.T02_Login@4dc27487]" started-at="2024-07-25T10:11:57 EEST" name="TestInvalidEmailLogin_N" finished-at="2024-07-25T10:11:58 EEST" duration-ms="782" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInvalidEmailLogin_N -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.T02_Login@4dc27487]" started-at="2024-07-25T10:11:58 EEST" name="tearDown" finished-at="2024-07-25T10:11:58 EEST" duration-ms="96" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.T02_Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
